create table "public"."cats" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "cat_name" text
);


CREATE UNIQUE INDEX cats_pkey ON public.cats USING btree (id);

alter table "public"."cats" add constraint "cats_pkey" PRIMARY KEY using index "cats_pkey";



